package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CIUDAD.
 */
public class Ciudad {

    private Long ciudadID;
    /** Not-null value. */
    private String nombreCiudad;
    private Double lowerLeftLatitude;
    private Double lowerLeftLongitude;
    private Double upperRightLatitude;
    private Double upperRightLongitude;
    private Double latitud;
    private Double longitud;
    private Integer zoom;

    public Ciudad() {
    }

    public Ciudad(Long ciudadID) {
        this.ciudadID = ciudadID;
    }

    public Ciudad(Long ciudadID, String nombreCiudad, Double lowerLeftLatitude, Double lowerLeftLongitude, Double upperRightLatitude, Double upperRightLongitude, Double latitud, Double longitud, Integer zoom) {
        this.ciudadID = ciudadID;
        this.nombreCiudad = nombreCiudad;
        this.lowerLeftLatitude = lowerLeftLatitude;
        this.lowerLeftLongitude = lowerLeftLongitude;
        this.upperRightLatitude = upperRightLatitude;
        this.upperRightLongitude = upperRightLongitude;
        this.latitud = latitud;
        this.longitud = longitud;
        this.zoom = zoom;
    }

    public Long getCiudadID() {
        return ciudadID;
    }

    public void setCiudadID(Long ciudadID) {
        this.ciudadID = ciudadID;
    }

    /** Not-null value. */
    public String getNombreCiudad() {
        return nombreCiudad;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }

    public Double getLowerLeftLatitude() {
        return lowerLeftLatitude;
    }

    public void setLowerLeftLatitude(Double lowerLeftLatitude) {
        this.lowerLeftLatitude = lowerLeftLatitude;
    }

    public Double getLowerLeftLongitude() {
        return lowerLeftLongitude;
    }

    public void setLowerLeftLongitude(Double lowerLeftLongitude) {
        this.lowerLeftLongitude = lowerLeftLongitude;
    }

    public Double getUpperRightLatitude() {
        return upperRightLatitude;
    }

    public void setUpperRightLatitude(Double upperRightLatitude) {
        this.upperRightLatitude = upperRightLatitude;
    }

    public Double getUpperRightLongitude() {
        return upperRightLongitude;
    }

    public void setUpperRightLongitude(Double upperRightLongitude) {
        this.upperRightLongitude = upperRightLongitude;
    }

    public Double getLatitud() {
        return latitud;
    }

    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    public Double getLongitud() {
        return longitud;
    }

    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    public Integer getZoom() {
        return zoom;
    }

    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }

}
