package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT.
 */
public class Client {

    private Long id;
    private String Client_Id;
    private String Name;
    private String Email;
    private String Phone;

    public Client() {
    }

    public Client(Long id) {
        this.id = id;
    }

    public Client(Long id, String Client_Id, String Name, String Email, String Phone) {
        this.id = id;
        this.Client_Id = Client_Id;
        this.Name = Name;
        this.Email = Email;
        this.Phone = Phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClient_Id() {
        return Client_Id;
    }

    public void setClient_Id(String Client_Id) {
        this.Client_Id = Client_Id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getPhone() {
        return Phone;
    }

    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

}
