package com.YozziBeens.rivostaxi.modelo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.YozziBeens.rivostaxi.modelo.Ciudad;
import com.YozziBeens.rivostaxi.modelo.Lugar;
import com.YozziBeens.rivostaxi.modelo.Client;
import com.YozziBeens.rivostaxi.modelo.ImagePerfil;
import com.YozziBeens.rivostaxi.modelo.Historial;
import com.YozziBeens.rivostaxi.modelo.HistorialPendiente;
import com.YozziBeens.rivostaxi.modelo.Favorite_Place;
import com.YozziBeens.rivostaxi.modelo.Favorite_Cabbie;
import com.YozziBeens.rivostaxi.modelo.Tarjeta;

import com.YozziBeens.rivostaxi.modelo.CiudadDao;
import com.YozziBeens.rivostaxi.modelo.LugarDao;
import com.YozziBeens.rivostaxi.modelo.ClientDao;
import com.YozziBeens.rivostaxi.modelo.ImagePerfilDao;
import com.YozziBeens.rivostaxi.modelo.HistorialDao;
import com.YozziBeens.rivostaxi.modelo.HistorialPendienteDao;
import com.YozziBeens.rivostaxi.modelo.Favorite_PlaceDao;
import com.YozziBeens.rivostaxi.modelo.Favorite_CabbieDao;
import com.YozziBeens.rivostaxi.modelo.TarjetaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ciudadDaoConfig;
    private final DaoConfig lugarDaoConfig;
    private final DaoConfig clientDaoConfig;
    private final DaoConfig imagePerfilDaoConfig;
    private final DaoConfig historialDaoConfig;
    private final DaoConfig historialPendienteDaoConfig;
    private final DaoConfig favorite_PlaceDaoConfig;
    private final DaoConfig favorite_CabbieDaoConfig;
    private final DaoConfig tarjetaDaoConfig;

    private final CiudadDao ciudadDao;
    private final LugarDao lugarDao;
    private final ClientDao clientDao;
    private final ImagePerfilDao imagePerfilDao;
    private final HistorialDao historialDao;
    private final HistorialPendienteDao historialPendienteDao;
    private final Favorite_PlaceDao favorite_PlaceDao;
    private final Favorite_CabbieDao favorite_CabbieDao;
    private final TarjetaDao tarjetaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ciudadDaoConfig = daoConfigMap.get(CiudadDao.class).clone();
        ciudadDaoConfig.initIdentityScope(type);

        lugarDaoConfig = daoConfigMap.get(LugarDao.class).clone();
        lugarDaoConfig.initIdentityScope(type);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        imagePerfilDaoConfig = daoConfigMap.get(ImagePerfilDao.class).clone();
        imagePerfilDaoConfig.initIdentityScope(type);

        historialDaoConfig = daoConfigMap.get(HistorialDao.class).clone();
        historialDaoConfig.initIdentityScope(type);

        historialPendienteDaoConfig = daoConfigMap.get(HistorialPendienteDao.class).clone();
        historialPendienteDaoConfig.initIdentityScope(type);

        favorite_PlaceDaoConfig = daoConfigMap.get(Favorite_PlaceDao.class).clone();
        favorite_PlaceDaoConfig.initIdentityScope(type);

        favorite_CabbieDaoConfig = daoConfigMap.get(Favorite_CabbieDao.class).clone();
        favorite_CabbieDaoConfig.initIdentityScope(type);

        tarjetaDaoConfig = daoConfigMap.get(TarjetaDao.class).clone();
        tarjetaDaoConfig.initIdentityScope(type);

        ciudadDao = new CiudadDao(ciudadDaoConfig, this);
        lugarDao = new LugarDao(lugarDaoConfig, this);
        clientDao = new ClientDao(clientDaoConfig, this);
        imagePerfilDao = new ImagePerfilDao(imagePerfilDaoConfig, this);
        historialDao = new HistorialDao(historialDaoConfig, this);
        historialPendienteDao = new HistorialPendienteDao(historialPendienteDaoConfig, this);
        favorite_PlaceDao = new Favorite_PlaceDao(favorite_PlaceDaoConfig, this);
        favorite_CabbieDao = new Favorite_CabbieDao(favorite_CabbieDaoConfig, this);
        tarjetaDao = new TarjetaDao(tarjetaDaoConfig, this);

        registerDao(Ciudad.class, ciudadDao);
        registerDao(Lugar.class, lugarDao);
        registerDao(Client.class, clientDao);
        registerDao(ImagePerfil.class, imagePerfilDao);
        registerDao(Historial.class, historialDao);
        registerDao(HistorialPendiente.class, historialPendienteDao);
        registerDao(Favorite_Place.class, favorite_PlaceDao);
        registerDao(Favorite_Cabbie.class, favorite_CabbieDao);
        registerDao(Tarjeta.class, tarjetaDao);
    }
    
    public void clear() {
        ciudadDaoConfig.getIdentityScope().clear();
        lugarDaoConfig.getIdentityScope().clear();
        clientDaoConfig.getIdentityScope().clear();
        imagePerfilDaoConfig.getIdentityScope().clear();
        historialDaoConfig.getIdentityScope().clear();
        historialPendienteDaoConfig.getIdentityScope().clear();
        favorite_PlaceDaoConfig.getIdentityScope().clear();
        favorite_CabbieDaoConfig.getIdentityScope().clear();
        tarjetaDaoConfig.getIdentityScope().clear();
    }

    public CiudadDao getCiudadDao() {
        return ciudadDao;
    }

    public LugarDao getLugarDao() {
        return lugarDao;
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public ImagePerfilDao getImagePerfilDao() {
        return imagePerfilDao;
    }

    public HistorialDao getHistorialDao() {
        return historialDao;
    }

    public HistorialPendienteDao getHistorialPendienteDao() {
        return historialPendienteDao;
    }

    public Favorite_PlaceDao getFavorite_PlaceDao() {
        return favorite_PlaceDao;
    }

    public Favorite_CabbieDao getFavorite_CabbieDao() {
        return favorite_CabbieDao;
    }

    public TarjetaDao getTarjetaDao() {
        return tarjetaDao;
    }

}
