package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE__PLACE.
 */
public class Favorite_Place {

    private Long id;
    private String PlaceFavoriteId;
    private String Name;
    private String Desc;
    private String Latitude;
    private String Longitude;

    public Favorite_Place() {
    }

    public Favorite_Place(Long id) {
        this.id = id;
    }

    public Favorite_Place(Long id, String PlaceFavoriteId, String Name, String Desc, String Latitude, String Longitude) {
        this.id = id;
        this.PlaceFavoriteId = PlaceFavoriteId;
        this.Name = Name;
        this.Desc = Desc;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlaceFavoriteId() {
        return PlaceFavoriteId;
    }

    public void setPlaceFavoriteId(String PlaceFavoriteId) {
        this.PlaceFavoriteId = PlaceFavoriteId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

}
