package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE__CABBIE.
 */
public class Favorite_Cabbie {

    private Long id;
    private String CabbieFavoriteId;
    private String Name;
    private String Company;

    public Favorite_Cabbie() {
    }

    public Favorite_Cabbie(Long id) {
        this.id = id;
    }

    public Favorite_Cabbie(Long id, String CabbieFavoriteId, String Name, String Company) {
        this.id = id;
        this.CabbieFavoriteId = CabbieFavoriteId;
        this.Name = Name;
        this.Company = Company;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCabbieFavoriteId() {
        return CabbieFavoriteId;
    }

    public void setCabbieFavoriteId(String CabbieFavoriteId) {
        this.CabbieFavoriteId = CabbieFavoriteId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getCompany() {
        return Company;
    }

    public void setCompany(String Company) {
        this.Company = Company;
    }

}
