package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORIAL.
 */
public class Historial {

    private Long id;
    private String Request_Id;
    private String Date;
    private String Cabbie_Name;
    private String Inicio;
    private String Destino;
    private String Ref;
    private String Cabbie;
    private String Price;

    public Historial() {
    }

    public Historial(Long id) {
        this.id = id;
    }

    public Historial(Long id, String Request_Id, String Date, String Cabbie_Name, String Inicio, String Destino, String Ref, String Cabbie, String Price) {
        this.id = id;
        this.Request_Id = Request_Id;
        this.Date = Date;
        this.Cabbie_Name = Cabbie_Name;
        this.Inicio = Inicio;
        this.Destino = Destino;
        this.Ref = Ref;
        this.Cabbie = Cabbie;
        this.Price = Price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRequest_Id() {
        return Request_Id;
    }

    public void setRequest_Id(String Request_Id) {
        this.Request_Id = Request_Id;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getCabbie_Name() {
        return Cabbie_Name;
    }

    public void setCabbie_Name(String Cabbie_Name) {
        this.Cabbie_Name = Cabbie_Name;
    }

    public String getInicio() {
        return Inicio;
    }

    public void setInicio(String Inicio) {
        this.Inicio = Inicio;
    }

    public String getDestino() {
        return Destino;
    }

    public void setDestino(String Destino) {
        this.Destino = Destino;
    }

    public String getRef() {
        return Ref;
    }

    public void setRef(String Ref) {
        this.Ref = Ref;
    }

    public String getCabbie() {
        return Cabbie;
    }

    public void setCabbie(String Cabbie) {
        this.Cabbie = Cabbie;
    }

    public String getPrice() {
        return Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

}
