package com.YozziBeens.rivostaxi.modelo;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.YozziBeens.rivostaxi.modelo.Historial;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HISTORIAL.
*/
public class HistorialDao extends AbstractDao<Historial, Long> {

    public static final String TABLENAME = "HISTORIAL";

    /**
     * Properties of entity Historial.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Request_Id = new Property(1, String.class, "Request_Id", false, "REQUEST__ID");
        public final static Property Date = new Property(2, String.class, "Date", false, "DATE");
        public final static Property Cabbie_Name = new Property(3, String.class, "Cabbie_Name", false, "CABBIE__NAME");
        public final static Property Inicio = new Property(4, String.class, "Inicio", false, "INICIO");
        public final static Property Destino = new Property(5, String.class, "Destino", false, "DESTINO");
        public final static Property Ref = new Property(6, String.class, "Ref", false, "REF");
        public final static Property Cabbie = new Property(7, String.class, "Cabbie", false, "CABBIE");
        public final static Property Price = new Property(8, String.class, "Price", false, "PRICE");
    };


    public HistorialDao(DaoConfig config) {
        super(config);
    }
    
    public HistorialDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HISTORIAL' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'REQUEST__ID' TEXT," + // 1: Request_Id
                "'DATE' TEXT," + // 2: Date
                "'CABBIE__NAME' TEXT," + // 3: Cabbie_Name
                "'INICIO' TEXT," + // 4: Inicio
                "'DESTINO' TEXT," + // 5: Destino
                "'REF' TEXT," + // 6: Ref
                "'CABBIE' TEXT," + // 7: Cabbie
                "'PRICE' TEXT);"); // 8: Price
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HISTORIAL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Historial entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Request_Id = entity.getRequest_Id();
        if (Request_Id != null) {
            stmt.bindString(2, Request_Id);
        }
 
        String Date = entity.getDate();
        if (Date != null) {
            stmt.bindString(3, Date);
        }
 
        String Cabbie_Name = entity.getCabbie_Name();
        if (Cabbie_Name != null) {
            stmt.bindString(4, Cabbie_Name);
        }
 
        String Inicio = entity.getInicio();
        if (Inicio != null) {
            stmt.bindString(5, Inicio);
        }
 
        String Destino = entity.getDestino();
        if (Destino != null) {
            stmt.bindString(6, Destino);
        }
 
        String Ref = entity.getRef();
        if (Ref != null) {
            stmt.bindString(7, Ref);
        }
 
        String Cabbie = entity.getCabbie();
        if (Cabbie != null) {
            stmt.bindString(8, Cabbie);
        }
 
        String Price = entity.getPrice();
        if (Price != null) {
            stmt.bindString(9, Price);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Historial readEntity(Cursor cursor, int offset) {
        Historial entity = new Historial( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Request_Id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Cabbie_Name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Inicio
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Destino
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Ref
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Cabbie
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // Price
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Historial entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRequest_Id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCabbie_Name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInicio(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDestino(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRef(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCabbie(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPrice(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Historial entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Historial entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
