package com.YozziBeens.rivostaxi.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT.
 */
public class AgregarHistorialCliente {


    public String getDate() {
        return Date;
    }

    public void setDate(String date) {
        Date = date;
    }

    public String getRef() {
        return Ref;
    }

    public void setRef(String ref) {
        Ref = ref;
    }

    public AgregarHistorialCliente(String date, String ref) {
        Date = date;
        Ref = ref;
    }

    public AgregarHistorialCliente() {
    }

    private String Date;
    private String Ref;




}
