package com.YozziBeens.rivostaxi.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT.
 */
public class TarjetaId {


    public TarjetaId(String card_Id) {
        Card_Id = card_Id;
    }

    public TarjetaId() {
    }

    public String getCard_Id() {
        return Card_Id;
    }

    public void setCard_Id(String card_Id) {
        Card_Id = card_Id;
    }

    private String Card_Id;





}
