package com.YozziBeens.rivostaxi.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT.
 */
public class TaxistasQueAtendieron {


    public TaxistasQueAtendieron(String name, String cabbie_Id) {
        Name = name;
        Cabbie_Id = cabbie_Id;
    }

    private String Name;

    public TaxistasQueAtendieron() {
    }

    private String Cabbie_Id;


    public String getCabbie_Id() {
        return Cabbie_Id;
    }

    public void setCabbie_Id(String cabbie_Id) {
        Cabbie_Id = cabbie_Id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }





}
