package com.YozziBeens.rivostaxi.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT.
 */
public class TaxistasCercanos {


    public TaxistasCercanos(String latitude, String longitude, String name, String cabbie_Id, String gcm_Id) {
        Latitude = latitude;
        Longitude = longitude;
        Name = name;
        Cabbie_Id = cabbie_Id;
        this.gcm_Id = gcm_Id;
    }
    public TaxistasCercanos() {
    }


    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String latitude) {
        Latitude = latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String longitude) {
        Longitude = longitude;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getCabbie_Id() {
        return Cabbie_Id;
    }

    public void setCabbie_Id(String cabbie_Id) {
        Cabbie_Id = cabbie_Id;
    }

    public String getGcm_Id() {
        return gcm_Id;
    }

    public void setGcm_Id(String gcm_Id) {
        this.gcm_Id = gcm_Id;
    }

    private String Latitude;
    private String Longitude;
    private String Name;
    private String Cabbie_Id;
    private String gcm_Id;



}
